package:
  name: asr_setup
  version: 0.7

build:
  number: 2
  preserve_egg_dir: True
  script: python setup.py install --single-version-externally-managed --record record.txt
  entry_points:
    - asr_setup = asr_setup.mainWindow:main

source:
    path: .

requirements:
  build:
    - python
    - setuptools
    
  run:
    - python
    - scipy
    - matplotlib
    - qtawesome
    - python-sounddevice
    - pydaqmx

about:
    home: https://bitbucket.org/randrian/asr_setup
    license: GPLv3
    license-family: GPL
    doc_url: http://asr_setup.readthedocs.io/
    dev_url: https://bitbucket.org/randrian/asr_setup
    summary: Acoustic startle response measurement